tag::ref-doc[]
= Splitter Processor
The splitter app builds upon the concept of the same name in Spring Integration and allows the splitting of a single
message into several distinct messages.

== Options
//tag::configuration-properties[]
$$splitter.apply-sequence$$:: $$Add correlation/sequence information in headers to facilitate later
 aggregation.$$ *($$Boolean$$, default: `$$true$$`)*
$$splitter.charset$$:: $$The charset to use when converting bytes in text-based files
 to String.$$ *($$String$$, default: `$$<none>$$`)*
$$splitter.delimiters$$:: $$When expression is null, delimiters to use when tokenizing
 {@link String} payloads.$$ *($$String$$, default: `$$<none>$$`)*
$$splitter.expression$$:: $$A SpEL expression for splitting payloads.$$ *($$Expression$$, default: `$$<none>$$`)*
$$splitter.file-markers$$:: $$Set to true or false to use a {@code FileSplitter} (to split
 text-based files by line) that includes
 (or not) beginning/end of file markers.$$ *($$Boolean$$, default: `$$<none>$$`)*
$$splitter.markers-json$$:: $$When 'fileMarkers == true', specify if they should be produced
 as FileSplitter.FileMarker objects or JSON.$$ *($$Boolean$$, default: `$$true$$`)*
//end::configuration-properties[]

When no `expression`, `fileMarkers`, or `charset` is provided, a `DefaultMessageSplitter` is configured with (optional) `delimiters`.
When `fileMarkers` or `charset` is provided, a `FileSplitter` is configured (you must provide either a `fileMarkers`
or `charset` to split files, which must be text-based - they are split into lines).
Otherwise, an `ExpressionEvaluatingMessageSplitter` is configured.

When splitting `File` payloads, the `sequenceSize` header is zero because the size cannot be determined at the beginning.

[CAUTION]
Ambiguous properties are not allowed.

== JSON Example

As part of the SpEL expression you can make use of the pre-registered JSON Path function. The syntax is
`#jsonPath(payload, '<json path expression>')`.

For example, consider the following JSON:

[source, json]
----
{ "store": {
    "book": [
        {
            "category": "reference",
            "author": "Nigel Rees",
            "title": "Sayings of the Century",
            "price": 8.95
        },
        {
            "category": "fiction",
            "author": "Evelyn Waugh",
            "title": "Sword of Honour",
            "price": 12.99
        },
        {
            "category": "fiction",
            "author": "Herman Melville",
            "title": "Moby Dick",
            "isbn": "0-553-21311-3",
            "price": 8.99
        },
        {
            "category": "fiction",
            "author": "J. R. R. Tolkien",
            "title": "The Lord of the Rings",
            "isbn": "0-395-19395-8",
            "price": 22.99
        }
    ],
    "bicycle": {
        "color": "red",
        "price": 19.95
    }
}}
----

and an expression `#jsonPath(payload, '$.store.book')`; the result will be 4 messages, each with a `Map` payload
containing the properties of a single book.

//end::ref-doc[]
== Building with Maven

```
$> mvn package
```
